Added hw12
ocherenkov/CPP-Course pull request #12
Opened 2024-01-22 07:53 UTC by ocherenkov

2024-01-29 18:30 UTC, helen-black requested changes

2024-01-29 18:30 UTC, helen-black commented on hw12/main.cpp
> +}
please, check your function with array, where ROWS = 4; COLUMNS = 3;

2024-01-30 12:25 UTC, ocherenkov commented on hw12/main.cpp
> +}
Tnx, fixed

2024-01-30 12:26 UTC, merged

2024-01-31 20:06 UTC, helen-black commented on hw12/main.cpp
> +            int column[COLUMNS * ROWS];
almost))
`int column[ROWS];`