Added hw6
ocherenkov/CPP-Course pull request #5
Opened 2024-01-18 17:03 UTC by ocherenkov

2024-01-22 20:30 UTC, helen-black requested changes

2024-01-22 20:30 UTC, helen-black commented on hw6/main.cpp
> +    } else {
wrong conditions. these parameters are valid:
-10, -10, 5
so you should print:
-10, -20, -30, -40, -50

only one valid check is the last input > 0

2024-01-22 20:30 UTC, helen-black commented on hw6/main.cpp
> +        for (int i = 1; i <= num; ++i) {
you can start this loop from 2

2024-01-22 20:30 UTC, helen-black commented on hw6/main.cpp
> +
it is 4.e (the same code as the next)

2024-01-22 20:30 UTC, helen-black commented on hw6/main.cpp
> +            std::cout << ((i + j) % 2 == 0 ? "1" : "0") << " ";
you can simplify it:
` std::cout << ((i + j) % 2 == 0);`

2024-01-23 10:35 UTC, ocherenkov commented on hw6/main.cpp
> +
Output is correct
Enter the shape size: 4
a:
****
***
**
*
b:
*
**
***
****
с:
****
 ****
  ****
   ****
d:
   ****
  ****
 ****
****
e:
1
01
101
0101

2024-01-24 09:23 UTC, helen-black approved these changes

2024-01-24 09:35 UTC, merged